const std = @import("std");
const ArrayList = std.ArrayList;
const zig = std.zig;
const testing = std.testing;
const mem = std.mem;
const Io = std.Io;

const parser = @import("parser.zig");
const protocol = @import("protocol.zig");

const log = std.log.scoped(.wayland_scanner);

pub const std_options = std.Options{
    .log_level = .info,
};

pub fn main(init: std.process.Init) !void {
    const args = try init.minimal.args.toSlice(init.gpa);
    defer init.gpa.free(args);

    var protocols: std.ArrayList(protocol.Protocol) = .empty;
    defer protocols.deinit(init.gpa);

    for (args[2..]) |path| {
        log.info("Parsing protocol: {s}", .{path});

        const file = try std.Io.Dir.openFileAbsolute(init.io, path, .{ .mode = .read_only });
        defer file.close(init.io);

        var buf: [2048]u8 = undefined;
        var input_reader = file.readerStreaming(init.io, &buf);

        try protocols.append(init.gpa, try parser.parse(init.arena.allocator(), &input_reader.interface));
    }

    log.info("Generating wayland protocol client at {s}", .{args[1]});

    const file = try std.Io.Dir.createFileAbsolute(init.io, args[1], .{});
    defer file.close(init.io);

    var buf: [2048]u8 = undefined;
    var client_writer = file.writer(init.io, &buf);

    const protocols_slice = try protocols.toOwnedSlice(init.gpa);
    defer init.gpa.free(protocols_slice);

    try generateClient(init.arena, &client_writer.interface, protocols_slice);

    try client_writer.flush();

    log.info("Completed generate wayland protocol client at {s}", .{args[1]});
}

pub fn generateClient(arena: *std.heap.ArenaAllocator, writer: *std.Io.Writer, protocols: []const protocol.Protocol) !void {
    const allocator = arena.allocator();

    try writer.writeAll(
        \\//! This file was automatically generated by the zimul Wayland scanner.
        \\// Any manual changes will be lost during the next build.
        \\
        \\const std = @import("std");
        \\const mem = std.mem;
        \\
        \\const common = @import("wayland_common");
        \\const inner = @import("wayland_client_core");
        \\
        \\const Client = @This();
        \\
    );

    var iface_prefix_map: std.StringHashMap([]const u8) = .init(allocator);
    defer iface_prefix_map.deinit();
    for (protocols) |proto| {
        const prefix = try protocolPrefix(allocator, proto.name);
        for (proto.interfaces.items) |iface| {
            try iface_prefix_map.put(iface.name, prefix);
        }
    }

    for (protocols) |proto| {
        const prefix = try protocolPrefix(allocator, proto.name);
        try writer.print("\n\npub const {s} = struct {{\n", .{prefix});
        for (proto.interfaces.items) |iface| {
            try generateInterface(allocator, writer, iface, prefix, iface_prefix_map);
        }
        try writer.writeAll("};\n");
    }
}

fn generateInterface(
    allocator: mem.Allocator,
    writer: *std.Io.Writer,
    interface: protocol.Interface,
    prefix: []const u8,
    prefix_map: std.StringHashMap([]const u8),
) !void {
    try writer.print(
        \\pub const {s} = opaque {{
        \\    const Self = @This();
        \\
        \\    const version: u32 = {d};
        \\
        \\
    , .{
        try pascalCase(allocator, interface.name),
        interface.version,
    });

    for (interface.requests.items, 0..) |request, i| {
        try generateRequest(allocator, writer, interface.name, request, i, prefix, prefix_map);
    }

    if (mem.eql(u8, interface.name, "wl_display")) {
        try writer.writeAll(generateDisplayClientApi());
    }

    try generateListener(allocator, writer, interface.name, interface.events, prefix, prefix_map);
    try generateEnumsV2(writer, allocator, interface.enums);

    try writer.print("\npub const interface: common.Interface = .{{\n    .name = \"{s}\",\n    .version = {d},\n    .method_count = {d},\n    .methods = &.{{ {s} }},\n    .event_count = {d},\n    .events = &.{{ {s} }},\n", .{
        interface.name,
        interface.version,
        interface.requests.items.len,
        try generateInterfaceMessages(allocator, interface.requests.items, prefix, prefix_map),
        interface.events.items.len,
        try generateInterfaceMessages(allocator, interface.events.items, prefix, prefix_map),
    });

    try writer.writeAll("};\n\n}; // Interface\n\n");
}

fn generateRequest(allocator: mem.Allocator, writer: *std.Io.Writer, interface_name: []const u8, request: protocol.Message, opcode: usize, prefix: []const u8, map: std.StringHashMap([]const u8)) !void {
    const request_name = try camelCase(allocator, request.name);
    const args = try generateArgs(allocator, snakeCase(interface_name), request.args, prefix, map);
    const return_type = try generateReturnType(allocator, request.args, prefix, map);
    var args_iter = mem.splitScalar(u8, args, ',');
    const first_arg = args_iter.first();
    var first_arg_iter = mem.splitScalar(u8, first_arg, ':');
    const first_arg_name = first_arg_iter.first();

    try writer.print(
        \\{s}
        \\pub fn {s}({s}) {s} {{
        \\
    , .{
        if (request.description) |desciption| blk: {
            var comment: ArrayList(u8) = .empty;

            if (desciption.summary) |sum| {
                try comment.print(allocator, "/// {s}.", .{sum});
            }

            if (desciption.description) |desc| {
                var lines = mem.splitScalar(u8, desc, '\n');
                while (lines.next()) |line| {
                    try comment.print(allocator, "\n/// {s}", .{mem.trim(u8, mem.trim(u8, line, "\t"), " ")});
                }
            }

            break :blk try comment.toOwnedSlice(allocator);
        } else "",
        request_name,
        args,
        if (mem.eql(u8, return_type, "void")) return_type else try mem.concat(allocator, u8, &[_][]const u8{ "!", return_type }),
    });

    if (mem.eql(u8, return_type, "void")) {
        try writer.print(
            \\const proxy: *inner.wl_proxy = @ptrCast(@alignCast({s}));
            \\_ = inner.wl_proxy.wl_proxy_marshal_flags(
            \\    proxy,
            \\    {d},
            \\    null,
            \\    inner.wl_proxy.wl_proxy_get_version(proxy),
            \\    0,
            \\    {s}
            \\);
            \\
        , .{ first_arg_name, opcode, try generateMarshallingArgs(allocator, request.args) });
    } else {
        try writer.print(
            \\const proxy: *inner.wl_proxy = @ptrCast(@alignCast({s}));
            \\const id = inner.wl_proxy.wl_proxy_marshal_flags(
            \\    proxy,
            \\    {d},
            \\    &{s}.interface,
            \\    inner.wl_proxy.wl_proxy_get_version(proxy),
            \\    0,
            \\    {s}
            \\) orelse return error.MarshalFailed;
            \\
            \\return @ptrCast(@alignCast(id));
            \\
        , .{ first_arg_name, opcode, mem.trimStart(u8, return_type, "*"), try generateMarshallingArgs(allocator, request.args) });
    }

    try writer.writeAll(
        \\}
        \\
        \\
    );
}

fn generateInterfaceMessages(allocator: mem.Allocator, messages: []protocol.Message, current_prefix: []const u8, map: std.StringHashMap([]const u8)) ![]const u8 {
    var list: std.ArrayList(u8) = .empty;

    for (messages) |msg| {
        try list.print(allocator,
            \\.{{
            \\    .name = "{s}",
            \\    .signature = "{s}",
            \\    .types = &.{{
            \\
        , .{ msg.name, try msg.signature(allocator) });

        for (msg.args.items) |arg| {
            if (arg.type == .new_id and arg.interface == null) {
                // Special case: untyped new_id counts as 3 args (s, u, n) in libwayland
                try list.appendSlice(allocator, "null,\n");
                try list.appendSlice(allocator, "null,\n");
                try list.appendSlice(allocator, "null,\n");
            } else if (arg.interface) |interface_name| {
                try list.print(allocator, "&{s}.interface,\n", .{try qualifiedPascalCase(allocator, interface_name, current_prefix, map)});
            } else {
                try list.appendSlice(allocator, "null,\n");
            }
        }
        try list.appendSlice(allocator,
            \\},
            \\
        );

        try list.appendSlice(allocator,
            \\},
            \\
        );
    }

    return list.toOwnedSlice(allocator);
}

fn generateEnums(allocator: mem.Allocator, enums: std.ArrayList(protocol.Enum), writer: *std.Io.Writer) !void {
    for (enums.items) |@"enum"| {
        const enum_name = try pascalCase(allocator, @"enum".name);

        try writer.writeAll(try std.fmt.allocPrint(allocator,
            \\pub const {s} = enum(u32) {{
            \\
        , .{enum_name}));

        for (@"enum".entries.items) |entry| {
            try writer.writeAll(try std.fmt.allocPrint(allocator,
                \\    {s} = {d},
                \\
            , .{ entry.name, entry.value }));
        }

        if (@"enum".bitfield) {
            try writer.print(
                \\    _,
                \\
                \\pub fn contains(self: {s}, other: {s}) bool {{
                \\    return @intFromEnum(self) & @intFromEnum(other) != 0;
                \\}}
                \\
                \\pub fn merge(self: {s}, other: {s}) {s} {{
                \\    return @enumFromInt(@intFromEnum(self) | @intFromEnum(other));
                \\}}
                \\
            , .{ enum_name, enum_name, enum_name, enum_name, enum_name });
        }

        try writer.writeAll(
            \\};
            \\
            \\
        );
    }
}

fn generateEnumsV2(writer: *Io.Writer, allocator: mem.Allocator, enums: ArrayList(protocol.Enum)) !void {
    for (enums.items) |enum_| {
        const enum_name = try pascalCase(allocator, enum_.name);

        if (enum_.bitfield) {
            try writer.print(
                \\pub const {s} = packed struct(u32) {{
                \\    const bitfield: bool = true;
                \\
                \\
            , .{enum_name});

            var bit_count: u6 = 0;
            for (enum_.entries.items) |entry| {
                std.log.info("value: {d}", .{entry.value});
                if (entry.value > 0 and std.math.isPowerOfTwo(entry.value)) {
                    bit_count += 1;
                    try writer.print("\t{f}: bool = false,\n", .{std.zig.fmtId(entry.name)});
                }
            }

            const padding: u6 = 32 - bit_count;
            if (bit_count > 0) {
                try writer.print("\n\t_padding: u{d} = 0,\n", .{padding});
            }

            try writer.writeAll("};\n\n");
        } else {
            try writer.print(
                \\pub const {s} = enum(u32) {{
                \\    const bitfield: bool = false;
                \\
                \\
            , .{enum_name});

            for (enum_.entries.items) |entry| {
                try writer.print("\t{s} = {d},\n", .{ entry.name, entry.value });
            }

            try writer.print("}};\n\n", .{});
        }
    }
}

fn generateMarshallingArgs(allocator: mem.Allocator, args: std.ArrayList(protocol.Arg)) ![]const u8 {
    var list: std.ArrayList(u8) = .empty;

    for (args.items) |arg| {
        if (arg.type == .new_id) {
            if (arg.interface == null) {
                // Untyped new_id: pass the interface name, version, and null (s, u, n in libwayland)
                try list.appendSlice(allocator, "T.interface.name, version_, @as(?*anyopaque, null), ");
            } else {
                // Fixed new_id: just pass mandatory null (n in libwayland)
                try list.appendSlice(allocator, "@as(?*anyopaque, null), ");
            }
        } else if (arg.@"enum" != null) {
            // Enums must be cast to their integer type before being passed
            try list.print(allocator, "@intFromEnum({s}), ", .{arg.name});
        } else {
            // Regular argument: just pass it as-is
            try list.print(allocator, "{s}, ", .{arg.name});
        }
    }

    return list.toOwnedSlice(allocator);
}

fn generateListener(allocator: mem.Allocator, writer: *std.Io.Writer, interface_name: []const u8, events: std.ArrayList(protocol.Message), current_prefix: []const u8, map: std.StringHashMap([]const u8)) !void {
    if (events.items.len == 0) return;

    try writeEventUnion(writer, allocator, current_prefix, map, events);
    try writeListenerStruct(allocator, writer, interface_name, events, current_prefix, map);
    try writeAddListenerSig(writer);
    try writeListenerInit(allocator, writer, events);
    try writeListenerWrappers(allocator, writer, interface_name, events, current_prefix, map);
    try writeAddListenerBody(writer);
}

fn writeEventUnion(
    writer: *Io.Writer,
    allocator: mem.Allocator,
    prefix: []const u8,
    map: std.StringHashMap([]const u8),
    events: std.ArrayList(protocol.Message),
) !void {
    try writer.writeAll(
        \\pub const Event = union(enum) {
        \\
    );

    for (events.items) |event| {
        try writer.print("{f}: struct {{ {s} }},\n", .{
            std.zig.fmtId(event.name),
            try generateArgsWithoutInterface(allocator, event.args, prefix, map),
        });

        if (mem.eql(u8, event.name, "release")) std.log.info("{any}", .{event.args.items});
    }

    try writer.writeAll("\n};\n\n");
}

fn writeListenerStruct(allocator: mem.Allocator, writer: *std.Io.Writer, interface_name: []const u8, events: std.ArrayList(protocol.Message), prefix: []const u8, map: std.StringHashMap([]const u8)) !void {
    _ = interface_name; // autofix
    try writer.writeAll("const Listener = extern struct {\n");
    for (events.items) |event| {
        const args = try generateArgsWithoutInterface(allocator, event.args, prefix, map);
        try writer.print("{f}: ?*const fn(data: ?*anyopaque, self: *Self, {s}) callconv(.c) void,\n", .{
            std.zig.fmtId(snakeCase(event.name)),
            args,
        });
    }
    try writer.writeAll("};\n\n");
}

fn writeAddListenerSig(writer: *std.Io.Writer) !void {
    try writer.writeAll(
        \\pub fn addListener(
        \\    self: *Self,
        \\    comptime T: type,
        \\    state: *T,
        \\    comptime listener_: fn (*Self, Event, *T) void,
        \\
    );
    try writer.writeAll(") !void {\n    const S = struct {\n");
}

fn writeListenerInit(allocator: mem.Allocator, writer: *std.Io.Writer, events: std.ArrayList(protocol.Message)) !void {
    try writer.writeAll("const listener = Self.Listener{\n");
    for (events.items) |event| {
        try writer.print(".{f} = {f},\n", .{ std.zig.fmtId(snakeCase(event.name)), std.zig.fmtId(try camelCase(allocator, event.name)) });
    }
    try writer.writeAll("};\n\n");
}

fn writeListenerWrappers(allocator: mem.Allocator, writer: *std.Io.Writer, interface_name: []const u8, events: std.ArrayList(protocol.Message), prefix: []const u8, map: std.StringHashMap([]const u8)) !void {
    _ = interface_name; // autofix
    for (events.items) |event| {
        const argsPairs = try generateArgsContextWithoutInterface(allocator, event.args, prefix, map);
        const fn_name = std.zig.fmtId(try camelCase(allocator, event.name));
        const fn_name_new = std.zig.fmtId(snakeCase(event.name));

        var params: std.ArrayList(u8) = .empty;
        var args: std.ArrayList(u8) = .empty;
        for (argsPairs) |pair| {
            try params.print(allocator, "{s}_: {s}, ", .{ pair.name, pair.type });
            try args.print(allocator, ".{s} = {s}_, ", .{ pair.name, pair.name });
        }

        try writer.print(
            \\fn {f}(data_: ?*anyopaque, self_: *Self{s} {s}) callconv(.c) void {{
            \\    listener_(self_, .{{ .{f} = .{{ {s} }} }}, @ptrCast(@alignCast(data_)));
            \\}}
            \\
        , .{
            fn_name,
            if (params.items.len == 0) "" else ", ",
            mem.trimEnd(u8, try params.toOwnedSlice(allocator), ", "),
            fn_name_new,
            mem.trimEnd(u8, try args.toOwnedSlice(allocator), ", "),
        });
    }
    try writer.writeAll("};\n");
}

fn writeAddListenerBody(writer: *std.Io.Writer) !void {
    try writer.writeAll(
        \\const proxy: *inner.wl_proxy = @ptrCast(@alignCast(self));
        \\if (inner.wl_proxy.wl_proxy_add_listener(proxy, @ptrCast(@alignCast(@constCast(&S.listener))), @ptrCast(@alignCast(state))) != 0) {
        \\    return error.AddListenerFailed;
        \\}
        \\
    );
    try writer.writeAll("}\n\n");
}

fn generateDisplayClientApi() []const u8 {
    return
    \\
    \\
    \\/// Connect to a Wayland display.
    \\pub inline fn connect(name: ?[*:0]const u8) !*Self {
    \\    return @ptrCast(@alignCast(inner.wl_display.wl_display_connect(name) orelse return error.ConnectionFailed));
    \\}
    \\
    \\/// Close a connection to a Wayland display.
    \\pub inline fn disconnect(self: *Self) void {
    \\    inner.wl_display.wl_display_disconnect(@ptrCast(@alignCast(self)));
    \\}
    \\
    \\/// Block until all pending request are processed by the server.
    \\pub inline fn roundtrip(self: *Self) !void {
    \\    if (inner.wl_display.wl_display_roundtrip(@ptrCast(@alignCast(self))) == -1)
    \\      return error.RoundtripFailed;
    \\}
    \\
    \\/// Process incoming events.
    \\pub inline fn dispatch(self: *Self) !void {
    \\    if (inner.wl_display.wl_display_dispatch(@ptrCast(@alignCast(self))) == -1)
    \\        return error.DispatchFailed;
    \\}
    \\
    \\
    ;
}

fn protocolPrefix(allocator: mem.Allocator, name: []const u8) ![]const u8 {
    if (mem.eql(u8, name, "wayland")) {
        return "Wl";
    } else if (mem.eql(u8, name, "xdg_shell")) {
        return "Xdg";
    } else if (mem.eql(u8, name, "tablet_v2")) {
        return error.UnsupportedProtocol;
    } else {
        return try pascalCase(allocator, name);
    }
}

fn qualifiedPascalCase(allocator: mem.Allocator, name: []const u8, current_prefix: []const u8, map: std.StringHashMap([]const u8)) ![]const u8 {
    const bare = try pascalCase(allocator, name);
    const target_prefix = map.get(name) orelse return bare;
    if (mem.eql(u8, target_prefix, current_prefix)) return bare;
    return try std.fmt.allocPrint(allocator, "{s}.{s}", .{ target_prefix, bare });
}

fn snakeCase(name: []const u8) []const u8 {
    if (std.mem.startsWith(u8, name, "wl_")) return name[3..];
    if (std.mem.startsWith(u8, name, "xdg_")) return name[4..];
    return name;
}

fn pascalCase(allocator: mem.Allocator, name: []const u8) ![]const u8 {
    var list: std.ArrayList(u8) = .empty;

    var capitalize_next = true;
    const stripped = if (std.mem.startsWith(u8, name, "wl_"))
        name[3..]
    else if (std.mem.startsWith(u8, name, "xdg_"))
        name[4..]
    else
        name;
    for (stripped) |c| {
        if (c == '_') {
            capitalize_next = true;
        } else if (c == '.') {
            try list.append(allocator, c);
            capitalize_next = true;
        } else {
            if (capitalize_next) {
                try list.append(allocator, std.ascii.toUpper(c));
                capitalize_next = false;
            } else {
                try list.append(allocator, std.ascii.toLower(c));
            }
        }
    }

    return list.toOwnedSlice(allocator);
}

fn camelCase(allocator: mem.Allocator, name: []const u8) ![]const u8 {
    var list: std.ArrayList(u8) = .empty;

    var capitalize_next = false;
    for (name) |c| {
        if (c == '_') {
            capitalize_next = true;
        } else {
            if (capitalize_next) {
                try list.append(allocator, std.ascii.toUpper(c));
                capitalize_next = false;
            } else {
                try list.append(allocator, std.ascii.toLower(c));
            }
        }
    }

    return list.toOwnedSlice(allocator);
}

const ArgPair = struct { name: []const u8, type: []const u8 };

fn argTypeString(allocator: mem.Allocator, arg: protocol.Arg, prefix: []const u8, map: std.StringHashMap([]const u8)) ![]const u8 {
    if (arg.@"enum") |@"enum"| {
        return try pascalCase(allocator, @"enum");
    }
    return switch (arg.type) {
        .int => "i32",
        .uint => "u32",
        .fixed => "common.Fixed",
        .string => if (arg.nullable) "?[*:0]const u8" else "[*:0]const u8",
        .object => if (arg.interface) |iname| blk: {
            const iface = try qualifiedPascalCase(allocator, iname, prefix, map);
            break :blk if (arg.nullable)
                try mem.concat(allocator, u8, &[_][]const u8{ "?*const ", iface })
            else
                try mem.concat(allocator, u8, &[_][]const u8{ "*const ", iface });
        } else "?*anyopaque",
        .array => if (arg.nullable) "?*common.Array" else "*common.Array",
        .new_id, .fd => unreachable, // handled by callers
    };
}

fn generateArgsContext(allocator: mem.Allocator, interface: []const u8, args: std.ArrayList(protocol.Arg), prefix: []const u8, map: std.StringHashMap([]const u8)) ![]ArgPair {
    var pairs: std.ArrayList(ArgPair) = .empty;

    try pairs.append(allocator, .{
        .name = snakeCase(interface),
        .type = try mem.concat(allocator, u8, &[_][]const u8{ "*", try pascalCase(allocator, interface) }),
    });
    outer: for (args.items) |arg| {
        if (arg.type == .new_id) {
            if (arg.interface == null) {
                try pairs.append(allocator, .{ .name = "T", .type = "type" });
            }
            continue :outer;
        }
        const arg_type = if (arg.type == .fd)
            "std.os.linux.fd_t"
        else
            try argTypeString(allocator, arg, prefix, map);
        try pairs.append(allocator, .{ .name = snakeCase(arg.name), .type = arg_type });
    }

    return pairs.toOwnedSlice(allocator);
}

fn generateArgsContextWithoutInterface(allocator: mem.Allocator, args: std.ArrayList(protocol.Arg), prefix: []const u8, map: std.StringHashMap([]const u8)) ![]ArgPair {
    var pairs: std.ArrayList(ArgPair) = .empty;

    outer: for (args.items) |arg| {
        if (arg.type == .new_id) {
            if (arg.interface == null) {
                try pairs.append(allocator, .{ .name = "T", .type = "type" });
            }
            continue :outer;
        }
        const arg_type = if (arg.type == .fd)
            "std.os.linux.fd_t"
        else
            try argTypeString(allocator, arg, prefix, map);
        try pairs.append(allocator, .{ .name = snakeCase(arg.name), .type = arg_type });
    }

    return pairs.toOwnedSlice(allocator);
}

fn generateArgs(allocator: mem.Allocator, interface: []const u8, args: std.ArrayList(protocol.Arg), prefix: []const u8, map: std.StringHashMap([]const u8)) ![]const u8 {
    var list: std.ArrayList(u8) = .empty;

    try list.print(allocator, "{s}: *{s}", .{ snakeCase(interface), try pascalCase(allocator, interface) });
    outer: for (args.items) |arg| {
        if (arg.type == .new_id) {
            if (arg.interface == null) {
                try list.appendSlice(allocator, ", comptime T: type, version_: u32");
            }
            continue :outer;
        }
        const arg_type = if (arg.type == .fd)
            "std.os.linux.fd_t"
        else
            try argTypeString(allocator, arg, prefix, map);
        try list.print(allocator, ", {s}: {s}", .{ arg.name, arg_type });
    }

    return list.toOwnedSlice(allocator);
}

fn generateArgsWithoutInterface(
    allocator: mem.Allocator,
    args: std.ArrayList(protocol.Arg),
    prefix: []const u8,
    map: std.StringHashMap([]const u8),
) ![]const u8 {
    var list: std.ArrayList(u8) = .empty;

    outer: for (args.items) |arg| {
        if (arg.type == .new_id) {
            if (arg.interface == null) {
                try list.appendSlice(allocator, ", comptime T: type");
            }
            continue :outer;
        }
        const arg_type = if (arg.type == .fd)
            "std.os.linux.fd_t"
        else
            try argTypeString(allocator, arg, prefix, map);
        try list.print(allocator, ", {s}: {s}", .{ arg.name, arg_type });
    }

    return mem.trimStart(u8, try list.toOwnedSlice(allocator), ",");
}

fn generateReturnType(allocator: mem.Allocator, args: std.ArrayList(protocol.Arg), current_prefix: []const u8, map: std.StringHashMap([]const u8)) ![]const u8 {
    for (args.items) |arg| {
        if (arg.type == .new_id) {
            if (arg.interface) |interface| {
                return try mem.concat(allocator, u8, &[_][]const u8{ "*", try qualifiedPascalCase(allocator, interface, current_prefix, map) });
            } else {
                return "*T";
            }
        }
    }
    return "void";
}

test "generate args" {
    testing.log_level = .debug;

    var arena: std.heap.ArenaAllocator = .init(testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    var args: std.ArrayList(protocol.Arg) = .empty;

    try args.append(allocator, .{
        .name = "arg1",
        .type = .int,
        .interface = null,
        .nullable = false,
        .@"enum" = null,
        .summary = null,
    });

    try args.append(allocator, .{
        .name = "arg2",
        .type = .string,
        .interface = null,
        .nullable = true,
        .@"enum" = null,
        .summary = null,
    });

    try args.append(allocator, .{
        .name = "arg3",
        .type = .object,
        .interface = "wl_surface",
        .nullable = false,
        .@"enum" = null,
        .summary = null,
    });

    try args.append(allocator, .{
        .name = "face",
        .type = .uint,
        .interface = null,
        .nullable = false,
        .@"enum" = "wl_data_device_manager.dnd_action",
        .summary = null,
    });

    try args.append(allocator, .{
        .name = "arg4",
        .type = .new_id,
        .interface = "wl_surface",
        .nullable = true,
        .@"enum" = null,
        .summary = null,
    });

    var iface_map = std.StringHashMap([]const u8).init(allocator);
    defer iface_map.deinit();
    const result = try generateArgs(allocator, snakeCase("wl_surface"), args, "Wl", iface_map);
    std.debug.print("Generated args: ({s})\n", .{result});
}

test "generate return type" {
    testing.log_level = .info;

    var arena: std.heap.ArenaAllocator = .init(testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    var args: std.ArrayList(protocol.Arg) = .empty;

    try args.append(allocator, .{
        .name = "arg1",
        .type = .int,
        .interface = null,
        .nullable = false,
        .@"enum" = null,
        .summary = null,
    });

    try args.append(allocator, .{
        .name = "arg2",
        .type = .new_id,
        .interface = "wl_surface",
        .nullable = true,
        .@"enum" = null,
        .summary = null,
    });

    var iface_map = std.StringHashMap([]const u8).init(allocator);
    defer iface_map.deinit();
    const result = try generateReturnType(allocator, args, "Wl", iface_map);
    std.debug.print("Generated return type: {s}\n", .{result});
}

test "generate enums" {
    testing.log_level = .info;

    var arena: std.heap.ArenaAllocator = .init(testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    var enums: std.ArrayList(protocol.Enum) = .empty;
    const entries = try allocator.dupe(protocol.Entry, &.{
        .{ .name = "argb8888", .value = 0, .since = 1, .summary = null, .description = null },
        .{ .name = "xrgb8888", .value = 1, .since = 1, .summary = null, .description = null },
        .{ .name = "c8", .value = 0x20203843, .since = 1, .summary = null, .description = null },
    });

    try enums.append(allocator, .{
        .name = "format",
        .entries = .fromOwnedSlice(entries),
        .bitfield = false,
        .description = null,
        .since = 1,
    });

    try enums.append(allocator, .{
        .name = "resize",
        .entries = .fromOwnedSlice(try allocator.dupe(protocol.Entry, &.{
            .{ .name = "none", .value = 0, .since = 1, .summary = null, .description = null },
            .{ .name = "top", .value = 1, .since = 1, .summary = null, .description = null },
            .{ .name = "bottom", .value = 2, .since = 1, .summary = null, .description = null },
            .{ .name = "left", .value = 4, .since = 1, .summary = null, .description = null },
            .{ .name = "top_left", .value = 5, .since = 1, .summary = null, .description = null },
            .{ .name = "bottom_left", .value = 6, .since = 1, .summary = null, .description = null },
            .{ .name = "right", .value = 8, .since = 1, .summary = null, .description = null },
            .{ .name = "top_right", .value = 9, .since = 1, .summary = null, .description = null },
            .{ .name = "bottom_right", .value = 10, .since = 1, .summary = null, .description = null },
        })),
        .bitfield = true,
        .description = null,
        .since = 1,
    });

    var buf: [1024]u8 = undefined;
    var stdout_writer = std.Io.File.stderr().writer(testing.io, &buf);
    const stdout = &stdout_writer.interface;

    try generateEnumsV2(stdout, allocator, enums);
    try stdout.flush();
}

test "generate" {
    testing.log_level = .info;

    var arena: std.heap.ArenaAllocator = .init(testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    var buf: [4096]u8 = undefined;

    const wl_file = try std.Io.Dir.openFileAbsolute(testing.io, "/usr/share/wayland/wayland.xml", .{ .mode = .read_only });
    defer wl_file.close(testing.io);

    var input_reader = wl_file.reader(testing.io, &buf);

    const wl_protocol = try parser.parse(allocator, &input_reader.interface);

    const xdg_file = try std.Io.Dir.openFileAbsolute(testing.io, "/usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml", .{ .mode = .read_only });
    defer xdg_file.close(testing.io);

    input_reader = xdg_file.reader(testing.io, &buf);

    const xdg_protocol = try parser.parse(allocator, &input_reader.interface);

    const out = try std.Io.Dir.cwd().createFile(testing.io, "src/wayland-scanner/wl.zig", .{ .read = true });
    defer out.close(testing.io);
    var file_writer = out.writer(testing.io, &buf);

    try generateClient(&arena, &file_writer.interface, &[_]protocol.Protocol{
        wl_protocol,
        xdg_protocol,
    });

    try file_writer.flush();
}
